### ISSUE TITLE
Minimum Tasks Checklist for the RTS Project

### ISSUE THREAD

**Issue by raysan5** [Needlesslord/BrainDeadStudios#1]
Following task should be completed for the project, please, add comments below if desired and reference big commits to the issue.

DESIGN
 - [x] GDD: Game Design Document [Docs/GDD.md](../blob/master/Docs/GDD.md)
 - [x] TDD: Tech Design Document [Docs/TDD.md](../blob/master/Docs/TDD.md)
 - [x] GUI Document [Docs/GUIDocument.md](../blob/master/Docs/GUIDocument.md)
 - [x] Art Bible [Docs/ArtBible.md](../blob/master/Docs/ArtBible.md)
 - [x] Audio Bible [Docs/AudioBible.md](../blob/master/Docs/AudioBible.md)
 - [x] QA Workflow [Docs/QAWorkflow.md](../blob/master/Docs/QAWorkflow.md)
 - [x] Production Plan [Docs/ProductionPlan.md](../blob/master/Docs/ProductionPlan.md)

GENERAL
 - [x] Screens transitions: fade-in/fade-out or better transitions (RS: Camera Transitions)
 - [x] GOD mode (F10): no-damage, fly-around mode, increase-resources...
 - [x] Game resolution: 1280x720px@60fps, support for windowed mode and fullscreen
 - [x] Custom game icon, custom mouse icon, executable properties (metadata) (RS: Installer)
 - [ ] Assets/Resources loaded from a ZIP (RS: Assets ZIP Management)
 - [x] Automatic Continuous Integration and Deployment (RS: Automatic CI + CD)

SCREEN: LOGO
 - [x] Logo implemented: custom art, avoid plain text
 - [x] ANIM: Animated Logo in/out (fading, movement…) (RS: Camera Transitions)
 - [x] AUDIO: Sound FX characteristic for the logo

SCREEN: TITLE
 - [x] Main game title implemented, custom art, avoid plain text
 - [x] Game SAVE/LOAD to/from external file
 - [x] ANIM: Title animation with easings (fading, movement…)
 - [x] AUDIO: Sound FX characteristic for the title appearing
 - [x] AUDIO: Music track specific for the screen
 - [x] UI: Main game menu implemented: START - CONTINUE - OPTIONS - EXIT
 - [x] UI: ANIM: Animated menu, responsive, visual feedback...
 - [x] UI: AUDIO: Buttons/UI fx feedback sounds

SCREEN: OPTIONS
 - [x] UI: Basic game config options implemented with custom font
 - [x] UI: OPTION1: Fullscreen mode selection
 - [x] UI: OPTION2: Music volume slider
 - [x] UI: OPTION3: Fx sounds volume slider
 - [x] ANIM: Animated options menu, responsive, visual feedback...
 - [x] AUDIO: Sound feedback for buttons and sliders
 - [x] AUDIO: Music track specific for the screen

SCREEN: GAMEPLAY
 - [x] Implement at least 3 types of Resources (RS: RTS Balancing)
 - [x] Implement at least 4 types of Playable Units (RS: RTS Balancing)
 - [x] Implement at least 3 Quests (RS: Quest Manager)
 - [x] Implement at least 4 Dialogs (RS: Dialog System)
 - [ ] Implement at least 5 Particle Systems (RS: Particle System)
 - [x] Implement group movement (RS: Group Movement)
 - [ ] Implement fog of war (RS: Fog of War)
 - [ ] INPUTS: Keyboard/Mouse inputs implemented
 - [x] UI: PAUSE menu available on pause
 - [x] UI: PAUSE menu animated with feedback (custom font)
 - [x] AUDIO: PAUSE menu in/out animation with audio feedback
 - [ ] UI: Minimap implemented and fully functional (RS: Minimap)
 - [x] UI: ANIM: Interface elements should be animated with visual feedback
 - [x] UI: AUDIO: Sound feedback for the interface elements (when required)
 - [x] AUDIO: Minimum of 15 fx game sounds implemented
 - [ ] AUDIO: Positioning in the scree: Volume effects (RS: Spatial Audio & Music Manager)
 - [x] AUDIO: Music track specific for the screen (RS: Spatial Audio & Music Manager)
 - [ ] AUDIO: Music effects fade-in/fade-out, lower volume on PAUSE

SCREEN: ENDING
 - [x] Custom background with victory/lose messages (custom font)
 - [x] ANIM: In/out animations (easings) for ending messages
 - [x] AUDIO: Sounds for messages and animations
 - [x] AUDIO: Music track specific for the screen

*NOTE: This checklist could change at any given point with added/deleted requirements.*

**Comment by raysan5** [comment]
Very good work! Nice to see you are linking your commits with the issue and you already completed some tasks! :)

**Comment by Needlesslord** [comment]
> Very good work! Nice to see you are linking your commits with the issue and you already completed some tasks! :)

Thank you for your kind words and encouragement! We are trying to link everything we have and we check afterwards if with the progress we make we have the task done ^^
